version: '3.9'

services:
  mongo:
    image: mongo:6.0.4
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes: 
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./todo-backend/mongo_data:/data/db
  redis:
    image: redis:7.0.8
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - ./todo-backend/redis_data:/data
  app:                    
    image: todo-backend   
    build: ./todo-backend/
    environment:
      - REDIS_URL=redis://redis:6379
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database
  web:
    image: todo-frontend
    build:
      context: ./todo-frontend/
      args:
        REACT_APP_BACKEND_URL: http://localhost:8080/api/
  nginx:
    container_name: reverse-proxy
    image: nginx:1.23.3-alpine
    volumes:
      - ./nginx.conf.template:/etc/nginx/templates/nginx.conf.template:ro
    ports:
      - 8080:80
    environment:
      WEB_URL: http://web:80
      NGINX_ENVSUBST_OUTPUT_DIR: /etc/nginx
    depends_on:
      - web
      - mongo
      - redis
      - app
