version: '3.9'

services:
  web:
    image: todo-frontend-dev
    build:
      context: ./todo-frontend/ 
      dockerfile: dev.Dockerfile
    volumes:
      - ./todo-frontend/:/usr/src/app 
    environment:
      REACT_APP_BACKEND_URL: http://localhost:8080/api
    container_name: todo-frontend-dev 
  nginx:
    image: nginx:1.23.3-alpine
    volumes:
      - ./nginx.conf.template:/etc/nginx/templates/nginx.conf.template:ro
    ports:
      - 8080:80
    environment:
      WEB_URL: http://web:80
      NGINX_ENVSUBST_OUTPUT_DIR: /etc/nginx
    container_name: reverse-proxy
    depends_on:
      - web

networks:
  default:
    name: todo-network
    external: true
